#' Metabolites within Subpathway Table
#' 
#' Return the test results for each metabolite within a subpathway.
#' 
#' @param path_results  Results data frame generated by \code{\link{subpathway_analysis}}
#' 
#' @param subpathway Character string of the subpathway of interest. This is case sensitive
#' and must be listed in the path_results.
#' 
#' @param mod model of interest. This can be a single model or a vector of model types
#' that can take on the values interaction,parallel, or single.
#' 
#' @returns a table with the results from the model types specified and for each 
#' metabolite within the superpathway specified.
#' 
#' @import dplyr
#' @import knitr
#' @import kableExtra
#' 
#' @export
#' 
#' 


met_within_sub <- function(path_results,subpathway,mod = c("interaction","parallel","single")){
  
  # create table
  table <- path_results %>% 
    dplyr::filter(sub_pathway=="Chemical") %>%
    dplyr::select(chem_name,all_of(paste0(mod,"_pval"))) %>%
    knitr::kable(digits = 3, col.names = c("Metabolite Name",str_to_title(paste0(mod," P-Value"))),caption = paste0("Metabolites within ",str_to_title(subpathway))) %>%
    kableExtra::kable_classic(full_width = F, html_font = "Cambria")
  
  return(table)

}
