#' Subpathway model type table
#' 
#' Create a table with the number of significant subpathways for each model type. 
#' 
#' @param path_results Results data frame generated by \code{\link{subpathway_analysis}}
#' 
#' @returns A table of the number of significant subpathways by model type.
#' 
#' @details
#' Each subpathway will only have one model type. We first test the interaction, 
#' then the parellel, and the Single model is tested last. If a subpathway has 
#' a significant interaction model type then the table will count it as a iteraction and
#' not as a parellel or single. 
#' 
#' 
#' @import dplyr
#' @import knitr
#' @import kableExtra
#' 
#' @export
#' 

subpath_by_model <- function(path_results){
  
  
  # 2. Structure levels
  if(sum(grepl("interaction",names(path_results)))==0){
    levs <- c("Single","None") 
  }
  if(!sum(grepl("interaction",names(path_results)))==0){ 
    levs =  c("Interaction", "Parallel", "Single", "None") 
  } 
  
  
  # 3. Create table data
  table_data <- path_results %>% 
    dplyr::mutate(model = factor(model, levels = levs)) %>%  
    dplyr::select(sub_pathway, ends_with("_fisher"), model) %>% 
    dplyr::distinct() 
  
  
  # 4. Create table
  sig_subPaths <- dplyr::count(table_data, model) %>% 
    dplyr::arrange((model)) %>% 
    knitr::kable(col.names = c("Model Type","Count"),
          caption = "Sigificant Pathways by Model")%>%
    kableExtra::kable_classic(full_width = F, html_font = "Cambria")
  
  # Return table
  return(sig_subPaths)
  
  
}