#' Proportion of Significant Subpathways Within Superpathways
#' 
#' Create a table that give the percentage of significant subpathways within each 
#' superpathway.
#' 
#' @param path_results Results data frame generated by \code{\link{subpathway_analysis}}
#' 
#' @returns A table with the proportion (and percent) of significant subpathways within superpathway.
#' 
#' @details
#' The numbers reported are the number of subpathways that were significant for any 
#' model. 
#' 
#' @import dplyr
#' @import knitr
#' @import kableExtra
#' 
#' @export
#' 


subpath_within_superpath <- function(path_results){
  
  
  # 2. Structure levels
  if(sum(grepl("interaction",names(path_results)))==0){ 
    levs <- c("Single","None") 
    
    cases <- expression( dplyr::case_when(model == "Single" ~ single_fisher)) 
  }
  if(!sum(grepl("interaction",names(path_results)))==0){ 
    levs =  c("Interaction", "Parallel", "Single", "None") 
    
    cases <- expression( dplyr::case_when(model == "Interaction" ~ interaction_fisher, 
                                   model == "Parallel" ~ parallel_fisher, 
                                   model == "Single" ~ single_fisher)) 
  }
  
  
  # 3. Create table data
  table_data <- path_results %>% 
    dplyr::mutate(model = factor(model, levels = levs)) %>% 
    dplyr::select(sub_pathway, ends_with("_fisher"), model) %>% 
    dplyr::distinct() #<3>
  
  
  # 4. Formulate the Super-pathway results table.
  superPath <- table_data %>% 
    dplyr::filter(model != "None") %>% 
    dplyr::mutate(pval = eval(cases)) %>% 
    dplyr::select(sub_pathway, pval) %>% 
    dplyr::right_join(chem_data %>% select(SUPER_PATHWAY, SUB_PATHWAY) %>% distinct(), 
               by = c("sub_pathway" = "SUB_PATHWAY"))  %>% 
    dplyr::filter(!is.na(sub_pathway)) %>% 
    dplyr::mutate(sig = ifelse(is.na(pval), 0, 1)) %>% 
    dplyr::group_by(SUPER_PATHWAY) %>% 
    dplyr::summarise(percent_significant = round(mean(sig) * 100, 2), 
              number_significant = sum(sig), 
              pathway_count = n()) %>%
    dplyr::ungroup() %>% dplyr::arrange(-percent_significant) %>%
    dplyr::transmute(SUPER_PATHWAY, percent_significant = paste0(number_significant, " / ", pathway_count,  
                                                          " (", percent_significant, "%)")) %>% 
    knitr::kable(col.names = c("Super Pathway", "Percent Significant"), 
                 caption = "Proportion of significant subpathways within super-pathways")%>%
    kableExtra::kable_classic(full_width = F, html_font = "Cambria")
  
  
  
  # Return table
  return(superPath)
  
}